version: '3'

services:
  web:
    build: .
    # command: ["flask", "run", "--host=0.0.0.0"]
    command: ["python3", "app.py"]
    volumes:
      - ./data:/app/instance
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
